---
  title: "Mark Scheid"
  tagline: "A little about me"
  author: 
    name: "Mark Scheid"
    email: "contact@wellcomposed.net"
    github: "scheidm"
  navigation: 
    - 
      text: "Projects"
      url: "/projects"
    - 
      text:  "Resume"
      url:  "/resume"
    - 
      text: "LinkedIn"
      url: "http://www.linkedin.com/pub/mark-scheid/90/a26/903"
    - 
      text: "GitHub"
      url: "https://github.com/scheidm"
  footer_links: 
    - 
      pretext: "built with "
      text: "Static Zen"
      url: "http://github.com/scheidm/static-zen"
      title: "The minimalist static page engine"
    - 
      pretext: "and "
      text: "Bootstrap"
      url: "http://twitter.github.com/bootstrap/"
      title: "The powerful CSS framework from Twitter"
  javascripts: 
    - 
      name: "bootstrap.min.js"
    - 
      name: "jquery.timeago.js"
  stylesheets: 
    - 
      name: "bootstrap.css"
    - 
      name: "dataTables.bootstrap.css"
    - 
      name: "google_prettify/prettify.css"
    - 
      name: "theme.css"
    - 
      name: "local.css"
  button_color: "#328597"
  description:
    default: "A little about me"
